name: VPS-Windows-2022-Azkhanh-ShowIP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: 1. Cài đặt Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath "tailscale-setup.exe" -ArgumentList "/quiet", "/norestart" -Wait
          
      - name: 2. Kết nối mạng Tailscale
        run: |
          # Đảm bảo bạn đã thêm TAILSCALE_AUTHKEY vào GitHub Secrets
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}
          
      - name: 3. Tạo User azkhanhkj_depzai
        run: |
          $User = "azkhanhkj_depzai"
          $Pass = "Namsoclo@2026" 
          net user $User $Pass /add
          net localgroup administrators $User /add
          net localgroup "Remote Desktop Users" $User /add
          Write-Host "User: $User | Pass: $Pass"

      - name: 4. HIỆN ĐỊA CHỈ IP ĐỂ KẾT NỐI
        run: |
          Write-Host "------------------------------------------"
          Write-Host "ĐANG LẤY ĐỊA CHỈ IP TAILSCALE..."
          # Lệnh lấy IP của card mạng Tailscale
          $tsIP = (Get-NetIPAddress -InterfaceAlias 'Tailscale' -AddressFamily IPv4).IPAddress
          Write-Host "ĐỊA CHỈ IP CỦA BẠN LÀ: $tsIP"
          Write-Host "------------------------------------------"
          Write-Host "Dùng IP này để đăng nhập vào Remote Desktop!"

      - name: 5. Duy trì máy (6 tiếng)
        run: |
          sleep 21600
