name: vps-azkhanhkj
on:
  workflow_dispatch: # Chạy bằng tay khi bạn muốn
  schedule:
    - cron: '0 */6 * * *' # Cứ mỗi 6 tiếng (00:00, 06:00, 12:00, 18:00 UTC) tự bật máy mới

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: 1. Cài đặt Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-setup.exe"
          Start-Process -FilePath "tailscale-setup.exe" -ArgumentList "/quiet", "/norestart" -Wait
          
      - name: 2. Kết nối mạng Tailscale
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}
          
      - name: 3. tao user
        run: |
          $User = "azkhanhkj_depzai"
          $Pass = "Namsoclo@2026" 
          net user $User $Pass /add
          net localgroup administrators $User /add
          net localgroup "Remote Desktop Users" $User /add

      - name: 4. anti vm
        run: |
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\CentralProcessor\0" /v "ProcessorNameString" /t REG_SZ /d "Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz" /f
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS" /v "SystemManufacturer" /t REG_SZ /d "ASUSTeK COMPUTER INC." /f
          reg add "HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS" /v "SystemProductName" /t REG_SZ /d "ROG STRIX Z490-E GAMING" /f
          Set-Service -Name "VMTools" -Status Stopped -ErrorAction SilentlyContinue

      - name: 5. ip
        run: |
          $DesktopPath = "C:\Users\azkhanhkj_depzai\Desktop"
          if (!(Test-Path $DesktopPath)) { New-Item -ItemType Directory -Path $DesktopPath }
          Invoke-WebRequest -Uri "https://www.roblox.com/download/client" -OutFile "$DesktopPath\RobloxPlayerLauncher.exe"
          
          Write-Host "------------------------------------------"
          $tsIP = (Get-NetIPAddress -InterfaceAlias 'Tailscale' -AddressFamily IPv4).IPAddress
          Write-Host "IP ĐỂ KẾT NỐI: $tsIP"
          Write-Host "User: azkhanhkj_depzai | Pass: Namsoclo@2026"
          Write-Host "------------------------------------------"

      - name: 6. duy trì
        run: |
          # 21600 giây = 6 tiếng
          sleep 21600
